### ISSUE TITLE
Generated Javascript for Telemetry View Widget, has a bug in it.

### ISSUE THREAD

**Issue by ModoDonuts** [OpenC3/cosmos#2498]
First check out our main documentation site at [https://openc3.com](https://openc3.com).

**Describe the bug**

When opening up the Telemetry view for any widget I get this error.

Chrome Browser console:
TypeError: Cannot read properties of undefined (reading 'includes')
    at Proxy.created (http://localhost:2900/tools/widgets/HelloWidget/HelloWidget.umd.min.js:1409:115619)
    at gn (http://localhost:2900/js/vue.global.prod-3.5.13.min.js:1:19821)
    at yn (http://localhost:2900/js/vue.global.prod-3.5.13.min.js:1:19881)
    at yn (http://localhost:2900/js/vue.global.prod-3.5.13.min.js:1:19988)
    at ei (http://localhost:2900/js/vue.global.prod-3.5.13.min.js:1:36395)
    at Rs (http://localhost:2900/js/vue.global.prod-3.5.13.min.js:1:65197)
    at U (http://localhost:2900/js/vue.global.prod-3.5.13.min.js:1:46263)
    at w (http://localhost:2900/js/vue.global.prod-3.5.13.min.js:1:41264)
    at qe.a [as fn] (http://localhost:2900/js/vue.global.prod-3.5.13.min.js:1:47270)
    at qe.run (http://localhost:2900/js/vue.global.prod-3.5.13.min.js:1:6949)

From Firefox browser console:
message: `can't access property "includes", this.parameters[2] is undefined`

**To Reproduce**
I followed the steps to create a custom widget found on the [Custom Widgets page](https://docs.openc3.com/docs/guides/custom-widgets). Without changing any code I simply uploaded my plugin into COSMOS, then opened the widget and then I get the screenshot below.

Docker containers are working fine, changes to Rakefile for pnpm work, and the gem file builds. I even tried using gem validator in the openc3.sh file to check if something was wrong, but that validated also.

If it helps, I created a more complex Vue component and it loads with this error as well. The UI loads, but I think the underlying javascript is broken.

**Expected behavior**
Widget opens without any errors

**Screenshots**

<img width="183" height="110" alt="Image" src="https://github.com/user-attachments/assets/1f805e25-1402-4a9f-a1e6-4f543416dc17" />
<img width="1178" height="297" alt="Image" src="https://github.com/user-attachments/assets/6fc9d59e-ec79-4c39-ba75-72c671dc9f25" />

**Environment (please complete the following information):**

- OS: Rhel 9.6
- OpenC3 COSMOS 6.2.1
- Browser: Chrome and Firefox

**Comment by ModoDonuts** [comment]
I also just realized that the Rakefile is trying to use `yarn`. It doesn't seem to be installed into the `openc3-node` container, could this be a possible reason for the issue?

Edit: never mind, I just looked at the [example Rakefile](https://github.com/OpenC3/cosmos/blob/main/openc3/templates/widget/Rakefile) and this looks exactly like the changes that I have made to get the Rakefile to run.

**Comment by ryanmelt** [comment]
pnpm is a very recent change.  6.2.1 used yarn.   Have you tried with 6.9.1?

**Comment by ModoDonuts** [comment]
Thanks for getting back to me.

I've run the openc3_upgrade.sh and run the new containers and everything seems fine on that front. But when I run:
`openc3.sh cli generate widget HelloWidget --python`

I'm now getting an error where package.json only contains the lines.
  "version": "6.9.1",
    "@openc3/vue-common": "6.9.1",

The rest of the package.json file doesn't seem to be generating for some reason.

**Comment by ModoDonuts** [comment]
Quick update:

Tried using the node `openc3-node` container that uses 6.2.1. Did the yarn install, yarn build, and the rake build. I'm still getting the same error as seen above.

I do have a question about `"vite-plugin-style-inject": "^0.0.1",` could this be causing some kind of issue? Because it's included in the `package.json` that comes with creating the widget scaffolding. It's generated in the vite.config.js, but isn't compatible with later version of vite. I did end up removing it from the project to get things to compile.

**Comment by ModoDonuts** [comment]
So what I'm tracking so far pertaining to widgets generation

Instructions to produce bugs version 6.2.1: 
1. Have a version of the COSMOS repo that's still in 6.2.1.
2. Generate generic plugin
3. Generate generic widget
  - yarn install
  - openc3.sh cli rake build VERSION=1.0.0
 
Error: `vite-plugin-style-inject": "^0.0.1` doesn't work with newer version of vite.
Workaround: remove `vite-plugin-style-inject` from vite.config.js and package.json. (This might be where I'm screwing up)

Rerun step 3 without `vite-plugin-style-inject`  artifacts.
4. Open custom widget

Error: Screenshots from above with Proxy object possibly not being defined.

Instructions to produce bugs version: 6.9.1
1. Download latest COSMOS repo
2. Generate generic plugin
3. Generate Widget

Error: package.json generation only contains 2 lines:
```
"version": "6.9.1",
    "@openc3/vue-common": "6.9.1",
```

**Comment by ryan-pratt** [comment]
@ModoDonuts, we've just released [v6.9.2](https://github.com/OpenC3/cosmos/releases/tag/v6.9.2) which should fix this issue with the generators

**Comment by ModoDonuts** [comment]
Hello again. The generator now works correctly with 6.9.2, but I'm still getting the same issue when running the widget. 

After working with someone who was more familiar with Vue, the issue is due to the generated code.


The error seems to be here in the generated code for the HelloWidget.vue
```
<script>
import { VWidget } from '@openc3/vue-common/widgets'

export default {
  mixins: [VWidget],
}
</script>
```

where as your documentation states (which is correct) 

```
<script>
import { Widget } from '@openc3/vue-common/widgets'

export default {
  mixins: [Widget],
}
</script>
```

Thank you for your patience as I'm new to both Vue as well as COSMOS.
